import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart' as maps;
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../../../core/models/activity_model.dart';
import '../../../../core/repositories/activity_repository.dart';
import '../../../../core/providers/core_providers.dart';

part 'create_activity_provider.g.dart';

/// State for the create activity wizard
class CreateActivityState {
  // Step 1: Info
  final String title;
  final String description;
  final String category;

  // Step 2: Location
  final GeoPoint? location;
  final String locationName;

  // Step 3: DateTime
  final DateTime? dateTime;

  // Step 4: Limits
  final int capacity;
  final double price;
  final bool isFree; // Helper to toggle price input
  final String? imageUrl; // For future use

  // UI State
  final bool isLoading;
  final String? error;

  const CreateActivityState({
    this.title = '',
    this.description = '',
    this.category = 'Other',
    this.location,
    this.locationName = '',
    this.dateTime,
    this.capacity = 10,
    this.price = 0,
    this.isFree = true,
    this.imageUrl,
    this.isLoading = false,
    this.error,
  });

  CreateActivityState copyWith({
    String? title,
    String? description,
    String? category,
    GeoPoint? location,
    String? locationName,
    DateTime? dateTime,
    int? capacity,
    double? price,
    bool? isFree,
    String? imageUrl,
    bool? isLoading,
    String? error,
  }) {
    return CreateActivityState(
      title: title ?? this.title,
      description: description ?? this.description,
      category: category ?? this.category,
      location: location ?? this.location,
      locationName: locationName ?? this.locationName,
      dateTime: dateTime ?? this.dateTime,
      capacity: capacity ?? this.capacity,
      price: price ?? this.price,
      isFree: isFree ?? this.isFree,
      imageUrl: imageUrl ?? this.imageUrl,
      isLoading: isLoading ?? this.isLoading,
      error: error, // Nullable to clear errors
    );
  }

  bool get isStep1Valid => title.isNotEmpty && category.isNotEmpty;
  bool get isStep2Valid => location != null && locationName.isNotEmpty;
  bool get isStep3Valid => dateTime != null; // Checks populated, shell enforces future if needed
  bool get isStep4Valid => capacity > 1; // At least 2 people (host + 1)
}

/// Provider for the create activity wizard
@riverpod
class CreateActivityNotifier extends _$CreateActivityNotifier {
  @override
  CreateActivityState build() {
    return const CreateActivityState();
  }

  // Setters for Step 1
  void setTitle(String value) => state = state.copyWith(title: value);
  void setDescription(String value) => state = state.copyWith(description: value);
  void setCategory(String value) => state = state.copyWith(category: value);

  // Setters for Step 2
  void setLocation(GeoPoint point, String name) {
    state = state.copyWith(location: point, locationName: name);
  }

  // Setters for Step 3
  void setDateTime(DateTime dt) => state = state.copyWith(dateTime: dt);

  // Setters for Step 4
  void setCapacity(int value) => state = state.copyWith(capacity: value);
  void setPrice(double value) => state = state.copyWith(price: value);
  void setIsFree(bool value) {
    state = state.copyWith(
      isFree: value,
      price: value ? 0 : state.price,
    );
  }

  // Submission
  Future<bool> createActivity() async {
    final user = ref.read(currentUserProvider);
    if (user == null) {
      state = state.copyWith(error: 'You must be logged in to create an activity');
      return false;
    }

    // Validation with specific errors
    if (!state.isStep1Valid) {
       state = state.copyWith(error: 'Missing Info: Title or Category required');
       return false;
    }
    if (!state.isStep2Valid) {
       state = state.copyWith(error: 'Missing Location: Please select a place');
       return false;
    }
    if (state.dateTime == null) {
       state = state.copyWith(error: 'Missing Time: Please select date and time');
       return false;
    }
    if (!state.isStep4Valid) {
       state = state.copyWith(error: 'Invalid Limits: Capacity must be > 1');
       return false;
    }

    state = state.copyWith(isLoading: true, error: null);

    try {
      final activity = ActivityModel(
        id: '', // Generated by repo
        title: state.title,
        description: state.description,
        category: state.category,
        hostId: user.uid,
        hostName: user.displayName,
        hostPhotoUrl: user.photoURL,
        location: state.location!,
        locationName: state.locationName,
        dateTime: state.dateTime!,
        capacity: state.capacity,
        price: state.isFree ? 0 : state.price,
        participants: [user.uid], // Host is first participant
        createdAt: DateTime.now(),
      );

      // Add timeout to prevent infinite hang (60 seconds for slow networks)
      await ref.read(activityRepositoryProvider).createActivity(activity)
          .timeout(
            const Duration(seconds: 60),
            onTimeout: () {
              throw Exception('Request timed out. Please check your connection.');
            },
          );
      
      // IMPORTANT: Explicitly set loading false BEFORE resetting state
      // This ensures the UI updates even if the full reset doesn't trigger rebuild
      state = state.copyWith(isLoading: false);
      
      // Small delay to ensure UI updates
      await Future.delayed(const Duration(milliseconds: 100));
      
      // Reset state on success
      state = const CreateActivityState();
      return true;
    } catch (e) {
      // Always ensure loading stops on error
      state = state.copyWith(isLoading: false, error: 'Failed to publish: ${e.toString()}');
      return false;
    }
  }
}
