// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_9RrLZPKZkxl3oy7_HumrTHXwnNYv_s0',
    appId: '1:976848239288:web:8c39b2e7438892fc42924d',
    messagingSenderId: '976848239288',
    projectId: 'loopout-7a874',
    authDomain: 'loopout-7a874.firebaseapp.com',
    storageBucket: 'loopout-7a874.firebasestorage.app',
    measurementId: 'G-YNM5LDSJ17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGjEi3rMPm14mAOrobOCcmjWsOW3MbWPk',
    appId: '1:976848239288:android:0ff699bd3109ecf142924d',
    messagingSenderId: '976848239288',
    projectId: 'loopout-7a874',
    storageBucket: 'loopout-7a874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnaBrY3AhsrZ1Q8eyDgO8KVr3lqd3RtKY',
    appId: '1:976848239288:ios:32f1c5499e0b0d9742924d',
    messagingSenderId: '976848239288',
    projectId: 'loopout-7a874',
    storageBucket: 'loopout-7a874.firebasestorage.app',
    iosBundleId: 'com.example.loopout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnaBrY3AhsrZ1Q8eyDgO8KVr3lqd3RtKY',
    appId: '1:976848239288:ios:32f1c5499e0b0d9742924d',
    messagingSenderId: '976848239288',
    projectId: 'loopout-7a874',
    storageBucket: 'loopout-7a874.firebasestorage.app',
    iosBundleId: 'com.example.loopout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_9RrLZPKZkxl3oy7_HumrTHXwnNYv_s0',
    appId: '1:976848239288:web:0a2cc453f6be487c42924d',
    messagingSenderId: '976848239288',
    projectId: 'loopout-7a874',
    authDomain: 'loopout-7a874.firebaseapp.com',
    storageBucket: 'loopout-7a874.firebasestorage.app',
    measurementId: 'G-54EN13WEWJ',
  );
}
